# Generated by Django 3.0.1 on 2021-02-11 03:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forecast', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='forecast',
            name='day1lbs',
            field=models.IntegerField(default=500),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='forecast',
            name='day2lbs',
            field=models.IntegerField(default=500),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='forecast',
            name='day3lbs',
            field=models.IntegerField(default=500),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='forecast',
            name='day4lbs',
            field=models.IntegerField(default=500),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='forecast',
            name='day5lbs',
            field=models.IntegerField(default=500),
            preserve_default=False,
        ),
    ]
