# Generated by Django 3.0.1 on 2021-02-11 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forecast', '0002_auto_20210211_0304'),
    ]

    operations = [
        migrations.AddField(
            model_name='forecast',
            name='lg5pct',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='forecast',
            name='med10pct',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='forecast',
            name='sm10pct',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='forecast',
            name='day1lbs',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='forecast',
            name='day2lbs',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='forecast',
            name='day3lbs',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='forecast',
            name='day4lbs',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='forecast',
            name='day5lbs',
            field=models.IntegerField(default=0),
        ),
    ]
