# Generated by Django 3.0.1 on 2021-02-12 22:38

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('forecast', '0004_forecast_updated'),
    ]

    operations = [
        migrations.AddField(
            model_name='forecast',
            name='shiftupdate',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='forecast',
            name='updated',
            field=models.DateField(),
        ),
    ]
