# Generated by Django 3.0.1 on 2021-02-12 22:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forecast', '0005_auto_20210212_1438'),
    ]

    operations = [
        migrations.AddField(
            model_name='forecast',
            name='eclass',
            field=models.CharField(blank=True, max_length=33, null=True),
        ),
    ]
