# Generated by Django 3.0.1 on 2021-02-12 23:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forecast', '0006_forecast_eclass'),
    ]

    operations = [
        migrations.AlterField(
            model_name='forecast',
            name='eclass',
            field=models.CharField(blank=True, default='not-saved', max_length=33, null=True),
        ),
    ]
